name: Build and Test GenAI Post Generator API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      

    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings -q

    - name: Build Docker Image
      run: docker build -t genai-post-api .

    - name: Run container and test API
      run: |
        docker run -d --name api_container -p 8080:8080 genai-post-api
        sleep 30  # Increased wait time for container startup
        curl --fail http://localhost:8080/ || (docker logs api_container && exit 1)
